### ISSUE TITLE
Any update on the "uninitialized constant Jquery::Ui::Rails::JQUERY_UI_VERSION" error?

### ISSUE THREAD

**Issue by brightball** [styx/jquery-ui-rails-cdn#3] opened 2013-09-27 17:42 UTC
I see the note about it in the readme, but it's been almost a year and this is the recommended gem from jquery-rails-cdn.

**Comment by styx** [comment] 2013-09-29 07:35
Seems, it will never be done. See https://github.com/joliss/jquery-ui-rails/pull/19 for details. There you will find some words why this gem is not OK in terms of compatibility and version will never be merged. I think I should add a note to the top of the README to not bother people more with this.

**Closed as completed by styx** 2013-09-29 07:35 UTC

**Comment by styx** [comment] 2013-09-29 07:38
I can only recommend you to use a more generic library https://github.com/lukehorvat/cdn_assets

**Comment by styx** [comment] 2013-10-26 06:19
Hey, great news! At last the issue is fixed! See readme file for details.
